name: My first workflow

on: push

jobs:
    first_run:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and read files
          run: |
            echo "Hello, GitHub Actions"
            ls -ltra
            cat README.md

        - name: Generare ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        # - name: List files
        #   run: ls 

        # - name: Read file
        #   run: cat README.md